apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: health
  namespace: istio-system
spec:
  hosts:
  - {{ printf "health-istiogw.%s" $.Values.ingress.prefix | quote }}
  gateways:
  - ingress-gateway-configuration
  http:
  - match:
    - uri:
        exact: /health
    directResponse:
      status: 200
      body:
        string: "OK"
