apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
spec:
  hosts:
    - {{ printf "kiali.%s" $.Values.ingress.prefix | quote }}
  gateways:
  - ingress-gateway-configuration
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ printf "kiali.%s.svc.cluster.local" $.Release.Namespace }}
        port:
          number: 20001
